language: objective-c

branches:
 only:
 - master

xcode_project: demo/demo.xcworkspace
xcode_scheme: demo/demoTests
osx_image: beta-xcode6.3
xcode_sdk: iphonesimulator8.4 

script:
- xcodebuild clean build test -project demo/demo.xcworkspace -scheme demo/demoTests