language: objective-c

branches:
 only:
 - master

xcode_project: demo.xcworkspace
xcode_scheme: demoTests
osx_image: beta-xcode6.3
xcode_sdk: iphonesimulator8.4 

script:
- xcodebuild clean build test -project demo.xcworkspace -scheme demoTests